import { createHash } from 'node:crypto'
import { existsSync, readFileSync, statSync, writeFileSync } from 'node:fs'
import { join, resolve, sep } from 'node:path'
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import { pagePaths, redirects } from './src/routes.js'

// Content-Security-Policy for production builds. It is added as a <meta> tag so
// it works on any static host: only this site's own scripts (plus the hashed
// inline theme script) may run, and only the listed services may be embedded.
function contentSecurityPolicy() {
  const policy = (scriptHashes) =>
    [
      "default-src 'self'",
      `script-src 'self' ${scriptHashes.map((h) => `'${h}'`).join(' ')}`,
      "style-src 'self' https://fonts.googleapis.com",
      "font-src 'self' https://fonts.gstatic.com",
      "img-src 'self' data: https://i.ytimg.com",
      'frame-src https://www.youtube-nocookie.com https://www.google.com https://maps.google.com',
      "connect-src 'self'",
      "object-src 'none'",
      "base-uri 'self'",
      "form-action 'self'",
      'upgrade-insecure-requests',
    ].join('; ')

  return {
    name: 'content-security-policy',
    apply: 'build',
    transformIndexHtml: {
      order: 'post',
      handler(html) {
        const inlineScripts = [...html.matchAll(/<script(?![^>]*\bsrc=)[^>]*>([\s\S]*?)<\/script>/g)]
        const hashes = inlineScripts.map(
          ([, code]) => `sha256-${createHash('sha256').update(code).digest('base64')}`,
        )
        return [
          {
            tag: 'meta',
            attrs: { 'http-equiv': 'Content-Security-Policy', content: policy(hashes) },
            injectTo: 'head-prepend',
          },
        ]
      },
    },
  }
}

// Serve the same headers as production (public/_headers) from `npm run preview`.
function hostHeaders() {
  const lines = readFileSync(new URL('./public/_headers', import.meta.url), 'utf8').split(/\r?\n/)
  return Object.fromEntries(
    lines
      .map((line) => line.trim())
      .filter((line) => line && !line.startsWith('#') && !line.startsWith('/'))
      .map((line) => [line.slice(0, line.indexOf(':')).trim(), line.slice(line.indexOf(':') + 1).trim()]),
  )
}

// Real 404s on a static host. The build writes:
//   404.html    a copy of the app; the host serves it, with HTTP status 404, for any unknown URL
//   _redirects  only the real pages (from src/routes.js) are rewritten to the app with status 200
// Netlify and Cloudflare Pages read both files automatically. `npm run preview`
// follows the same rules, so status codes can be checked locally.
function notFoundPages(headers) {
  let outDir

  const normalize = (path) => (path.length > 1 && path.endsWith('/') ? path.slice(0, -1) : path)
  const isPage = (path) => pagePaths.includes(normalize(path))
  const isFile = (path) => {
    try {
      const file = resolve(outDir, `.${decodeURIComponent(path)}`)
      return file.startsWith(outDir + sep) && existsSync(file) && statSync(file).isFile()
    } catch {
      return false // malformed %-encoding
    }
  }

  return {
    name: 'not-found-pages',
    configResolved(config) {
      outDir = resolve(config.root, config.build.outDir)
    },
    writeBundle() {
      writeFileSync(join(outDir, '404.html'), readFileSync(join(outDir, 'index.html')))
      const rules = [
        '# Generated by vite.config.js from src/routes.js. Do not edit by hand.',
        '# Real pages load the app (200). Any other URL gets 404.html with status 404.',
        // Paths of real files (e.g. /index.html) are served by the host as-is; the app redirects those itself.
        ...Object.entries(redirects)
          .filter(([from]) => !/\.\w+$/.test(from))
          .map(([from, to]) => `${from}  ${to}  301`),
        ...pagePaths.filter((p) => p !== '/').flatMap((p) => [`${p}  /index.html  200`, `${p}/  /index.html  200`]),
      ]
      writeFileSync(join(outDir, '_redirects'), `${rules.join('\n')}\n`)
    },
    configurePreviewServer(server) {
      server.middlewares.use((req, res, next) => {
        // Raw path, not new URL(): that would read "//evil.example" as another host.
        const path = req.url.split(/[?#]/)[0]
        if (isPage(path) || isFile(path)) return next()
        const target = redirects[normalize(path)]
        res.writeHead(target ? 301 : 404, {
          ...headers,
          ...(target ? { Location: target } : { 'Content-Type': 'text/html; charset=utf-8' }),
        })
        res.end(target ? undefined : readFileSync(join(outDir, '404.html')))
      })
    },
  }
}

export default defineConfig({
  plugins: [react(), contentSecurityPolicy(), notFoundPages(hostHeaders())],
  server: {
    port: 5173,
  },
  preview: {
    headers: hostHeaders(),
  },
})
